css-brochure-form
sinadaryaei/c0323-code-solutions pull request #28
Opened 2023-03-29 23:11 UTC by sinadaryaei

![image](https://user-images.githubusercontent.com/125223265/228688050-f11cda84-f395-41f6-874a-0fb091239051.png)

2023-04-03 16:38 UTC, shawnkost requested changes
Some changes requested here Sina!

2023-04-03 16:38 UTC, shawnkost commented on css-brochure-form/index.html
> +      <input type="text" name="Name" placeholder="sally@company.co" />
This `input` needs a `label` associated with it. I would turn the text on line 18 into a `label`, and link the two using a `for` attribute.

2023-04-03 16:38 UTC, shawnkost commented on css-brochure-form/index.html
> +      <input type="text" name="Name" placeholder="Sally Smith"/>
This `input` needs a `label` associated with it. I would turn the text on line 22 into a `label`, and link the two using a `for` attribute.

2023-04-03 16:38 UTC, shawnkost commented on css-brochure-form/index.html
> +      <input type="text" name="Name" placeholder="City, Country" />
This `input` needs a `label` associated with it. I would turn the text on line 26 into a `label`, and link the two using a `for` attribute.

2023-04-03 16:38 UTC, shawnkost commented on css-brochure-form/index.html
> +      <select name="Select an option">
This `select` needs a `label` associated with it. I would turn the text on line 30 into a `label`, and link the two using a `for` attribute.

2023-04-03 16:43 UTC, sinadaryaei commented
Thank you!

2023-04-04 15:35 UTC, shawnkost approved these changes
👍🏻

2023-04-04 23:04 UTC, merged