Css box model - Sina Daryaei
sinadaryaei/c0323-code-solutions pull request #29
Opened 2023-03-29 23:29 UTC by sinadaryaei

![image](https://user-images.githubusercontent.com/125223265/228690286-014c5c2b-6017-46e6-8b60-7d623e7ab7f1.png)

2023-03-30 17:20 UTC, shawnkost requested changes
One change requested here Sina!

2023-03-31 03:26 UTC, sinadaryaei commented on css-box-model/styles.css
> +  border-radius: 6px;
Can I use padding as shorthand?

2023-03-31 14:59 UTC, shawnkost requested changes
The padding values are incorrect here! Top / bottom should have the same value, same with left / right

2023-03-31 14:59 UTC, shawnkost commented on css-box-model/styles.css
> +  padding: 10px 15px 20px 25px;
Your padding values are incorrect. Look back at the message I sent you last night

2023-03-31 16:26 UTC, shawnkost approved these changes
👍🏻

2023-03-31 16:26 UTC, merged