Css three column layout - Sina Daryaei
sinadaryaei/c0323-code-solutions pull request #33
Opened 2023-03-31 05:37 UTC by sinadaryaei

![image](https://user-images.githubusercontent.com/125223265/229032164-55d264e6-a06c-4fde-a15d-dd44a338e666.png)

I know it doesn't look like the example.png... I need help ironing things out...

2023-04-03 16:50 UTC, shawnkost requested changes
Some changes requested here Sina!

2023-04-03 16:50 UTC, shawnkost commented on css-three-column-layout/index.html
> +    </header>
What's the point of this, if you don't have any text inside of it? Should the `h1` on line 13 go inside here?

2023-04-03 16:50 UTC, shawnkost commented on css-three-column-layout/styles.css
> +  width: 80%;
You set the `width` to 80%, but then you set the `max-width` to 50%. You shouldn't set a `width` that is bigger than your `max-width`.

2023-04-03 16:50 UTC, shawnkost commented on css-three-column-layout/styles.css
> +  flex-basis: 50%;
This shouldn't be 50%. If you have 3 columns, you cant have all of them take up 50% right? You should do `flex-basis: calc(100% / 3)`

2023-04-03 16:50 UTC, shawnkost commented on css-three-column-layout/styles.css
> +  font-size: 150%;
I don't recommend using percents for font-size. You should use either `rem` or `px`.

2023-04-03 16:54 UTC, sinadaryaei commented
Thank you, I'll make those changes.

2023-04-04 15:36 UTC, shawnkost approved these changes
👍🏻

2023-04-04 23:04 UTC, merged